---
# Cloudera playbook
- name: Install Cloudera Manager Server
  hosts: scm_server
  roles:
    - scm
  tags: cluster_template

- name: Install CDH
  hosts: scm_server
  roles:
    - cdh
  tags: cluster_template

